### ISSUE TITLE
Two functions doing almost the same thing

### ISSUE THREAD

**Issue by lisamdespain** [BloomTech-Labs/coder-heroes-be#123]
This is for profileMiddleware.js. One function, checkProfileExist, checks for a profile based on profile_id. The other, checkProfileExists, checks for a profile based on okta_id. Could 1 function do what both these functions are doing?

RM Edit: We could certainly iron out which model we want to work off of in a more holistic manner, from front-end to back-end - then remove the unnecessary function. I think we likely don't need to be searching for profiles both ways!

**Comment by paulstgermain** [comment]
We could certainly iron out which model we want to work off of in a more holistic manner, from front-end to back-end - then remove the unnecessary function. I think we likely don't need to be searching for profiles both ways!
